version: '3'
services: 
    app:
        build: .
        ports: 
            - "3000:3000"
        environment:
            REDIS_PASSWORD: password123
        volumes:
            - "$PWD/config.json:/app/config.json"
    redis:
        image: "bitnami/redis:latest"
        ports:
            - "6379:6379"
        environment:
            REDIS_PASSWORD: password123